# Generated by Django 5.2 on 2025-04-16 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApiKey',
        ),
    ]
