# Generated by Django 5.0.3 on 2025-05-30 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institutions',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('bic', models.CharField(max_length=20)),
                ('transaction_total_days', models.PositiveIntegerField()),
                ('max_access_valid_for_days', models.PositiveIntegerField()),
                ('logo', models.URLField()),
                ('countries', models.JSONField()),
            ],
        ),
    ]
