# Generated by Django 5.0.3 on 2025-06-01 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking_api', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=34)),
                ('alias', models.CharField(blank=True, max_length=100, null=True)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='users.account')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banking_api.institutions')),
            ],
            options={
                'unique_together': {('account', 'account_number')},
            },
        ),
    ]
